services:
  booktestapi:
    build: ./BookTestApi
    container_name: booktestapi
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db1:5432/testCrudApp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka2:8761/eureka/
      - SERVER_PORT=8080
    depends_on:
      db1:
        condition: service_started
      eureka2:
        condition: service_healthy
    networks:
      - my_network

  libraryservice:
    build: ./LibraryService
    container_name: libraryservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2:5432/LibraryService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka2:8761/eureka/
      - SERVER_PORT=8081
    depends_on:
      db2:
        condition: service_started
      eureka2:
        condition: service_healthy
    networks:
      - my_network

  identity-service:
    build: ./IdentityService
    container_name: identity-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db3:5432/Users
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka2:8761/eureka/
    depends_on:
      db3:
        condition: service_started
      eureka2:
        condition: service_healthy
    networks:
      - my_network

  gatewayserver:
    build: ./GatewayServer
    container_name: gatewayserver
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka2:8761/eureka/
    depends_on:
      eureka2:
        condition: service_healthy
    networks:
      - my_network

  eureka2:
    build: ./EurekaService
    container_name: eureka2
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/" ]
      interval: 10s
      timeout: 10s
      retries: 3

  db1:
    image: postgres:13
    container_name: db1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testCrudApp
    ports:
      - "5433:5432"
    networks:
      - my_network

  db2:
    image: postgres:13
    container_name: db2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=LibraryService
    ports:
      - "5434:5432"
    networks:
      - my_network

  db3:
    image: postgres:13
    container_name: db3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=Users
    ports:
      - "5435:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
