spring:
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
        - id: book-service
          uri: lb://TESTCRUDAPP
          predicates:
            - Path=/books/**
          filters:
            - AuthenticationFilter
        - id: book-service1
          uri: lb://TESTCRUDAPP
          predicates:
            - Path=/books
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
